# Generated by Django 4.1.1 on 2022-11-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Monitor', 'Monitor'), ('Peripheral', 'Peripheral'), ('Laptop', 'Laptop')], max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Deployed and Working', 'Deployed and Working'), ('Not deployed but working', 'Not deployed but working'), ('Not Working', 'Not Working'), ('Under Repair', 'Under Repair')], max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Assets',
            },
        ),
    ]
