# Generated by Django 4.1.1 on 2022-10-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('1', 'CPU'), ('2', 'Monitor'), ('3', 'Peripheral'), ('4', 'Laptop')], max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Deployed and Working'), ('2', 'Not deployed but working'), ('3', 'Not Working'), ('4', 'Under Repair')], max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Assets',
            },
        ),
    ]
