# Generated by Django 4.1.1 on 2022-10-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Monitor', 'Monitor'), ('Peripheral', 'Peripheral'), ('Laptop', 'Laptop')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(blank=True, choices=[('Deployed and Working', 'Deployed and Working'), ('Not deployed but working', 'Not deployed but working'), ('Not Working', 'Not Working'), ('Under Repair', 'Under Repair')], max_length=50, null=True),
        ),
    ]
