# Generated by Django 4.1.1 on 2022-11-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(blank=True, choices=[('CPUs', 'CPUs'), ('Monitors', 'Monitors'), ('Peripherals', 'Peripherals'), ('Laptop', 'Laptop'), ('Printers', 'Printers'), ('Adapters', 'Adapters')], max_length=50, null=True),
        ),
    ]
