# Generated by Django 4.1.1 on 2022-10-06 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('issue', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.CharField(choices=[('1', 'Pending'), ('2', 'Open'), ('3', 'Progress'), ('4', 'Closed')], default=('1', 'Pending'), max_length=50)),
                ('category', models.CharField(choices=[('1', 'Software'), ('2', 'Hardware'), ('3', 'Liveware'), ('4', 'Server')], default=('1', 'Software'), max_length=50)),
                ('verification', models.BooleanField(blank=True, null=True)),
                ('date_closed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
