# Generated by Django 4.1.1 on 2022-11-29 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='expert_pics/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Amateur', 'Amateur'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance'), ('Pro', 'Pro')], default='Beginner', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('issue', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High'), ('Very High', 'Very High')], default='Low', max_length=100)),
                ('date', models.DateField(null=True)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=100)),
                ('submitter_name', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ticket_pics')),
                ('description', models.TextField(blank=True, null=True)),
                ('anydesk', models.CharField(blank=True, max_length=9, null=True)),
                ('time', models.TimeField(default='08:34:45')),
                ('cycle', models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Progress', 'Progress'), ('Closed', 'Closed')], default='Pending', max_length=100)),
                ('category', models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Liveware', 'Liveware'), ('Server', 'Server')], default='Software', max_length=100)),
                ('verification', models.BooleanField(blank=True, null=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('documentation', models.TextField(blank=True)),
                ('assigned_to', models.ManyToManyField(to='tickets.expert')),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='tickets.specialization'),
        ),
    ]
