# Generated by Django 4.1.1 on 2022-10-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_closed',
            field=models.DateTimeField(),
        ),
    ]
