# Generated by Django 4.1.1 on 2022-11-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branches',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='zones',
            options={'verbose_name_plural': 'Zones'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='branch',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='12:13:39'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='zone',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
