# Generated by Django 4.1.1 on 2022-10-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_category_alter_ticket_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Liveware', 'Liveware'), ('Server', 'Server')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='16:35:50'),
        ),
    ]
