# Generated by Django 4.1.1 on 2022-11-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_branches_options_alter_zones_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='12:21:55'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='zone',
            field=models.CharField(choices=[('Basse', 'Basse')], max_length=100),
        ),
    ]
