# Generated by Django 4.1.1 on 2022-11-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_time_alter_ticket_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='13:35:10'),
        ),
    ]
