# Generated by Django 4.1.1 on 2022-11-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_time_alter_ticket_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='14:28:33'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='zone',
            field=models.CharField(choices=[('Bansang', 'Bansang'), ('Basse', 'Basse'), ('Brikama', 'Brikama'), ('Brusibi', 'Brusibi'), ('Soma', 'Soma'), ('Tabokoto', 'Tabokoto'), ('Tippagarage', 'Tippagarage'), ('Westfield', 'Westfield')], max_length=100),
        ),
    ]
