# Generated by Django 4.1.1 on 2022-12-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_alter_profile_profile_pic_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='20:35:53'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
