# Generated by Django 4.1.1 on 2022-10-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[(' ', ' '), ('Sage Jawla', 'Sage Jawla')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='22:06:40'),
        ),
    ]
