# Generated by Django 4.1.1 on 2022-10-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_alter_ticket_assigned_to_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('Lamin Jawla', 'Lamin Jawla'), ('Sage Jawla', 'Sage Jawla')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='22:08:30'),
        ),
    ]
