# Generated by Django 4.1.1 on 2022-10-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_ticket_assigned_to_alter_ticket_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('App Developer', 'App Developer'), ('Cyber Security', 'Cyber Security'), ('Computer network architects', 'Computer network architects'), ('Computer support specialists', 'Computer support specialists'), ('Data management', 'Data management'), ('IT Manager', 'IT Manager'), ('IT infrastructure', 'IT infrastructure'), ('IT project managers', 'IT project managers'), ('IT support', 'IT support'), ('Information security analysts', 'Information security analysts'), ('Server Aministration', 'Server Aministration'), ('Software Engineer', 'Software Engineer'), ('Social Media Manager', 'Social Media Manager'), ('Transaction Portal Administration', 'Transaction Portal Administration'), ('Web Developer', 'Web Developer'), ('Other', 'Other')], max_length=100)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Amateur', 'Amateur'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance'), ('Pro', 'Pro')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='09:10:03'),
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.ManyToManyField(to='tickets.specialization')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ManyToManyField(to='tickets.expert'),
        ),
    ]
