# Generated by Django 4.1.1 on 2022-10-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_alter_ticket_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='level',
        ),
        migrations.AddField(
            model_name='expert',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Amateur', 'Amateur'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance'), ('Pro', 'Pro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='09:18:12'),
        ),
    ]
