# Generated by Django 4.1.1 on 2022-10-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_remove_specialization_level_expert_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='field',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='09:38:16'),
        ),
    ]
