# Generated by Django 4.1.1 on 2022-10-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_alter_ticket_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='expert',
            name='tasks',
            field=models.ManyToManyField(to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='09:45:42'),
        ),
    ]
