# Generated by Django 4.1.1 on 2022-10-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_remove_ticket_assigned_to_expert_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='tasks',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ManyToManyField(to='tickets.expert'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='09:47:18'),
        ),
    ]
