# Generated by Django 4.1.1 on 2022-10-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Amateur', 'Amateur'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance'), ('Pro', 'Pro')], default='Beginner', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Liveware', 'Liveware'), ('Server', 'Server')], default='Software', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High'), ('Very High', 'Very High')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='15:18:27'),
        ),
    ]
