# Generated by Django 4.1.1 on 2022-10-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_alter_expert_level_alter_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cycle',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Progress', 'Progress'), ('Closed', 'Closed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='15:19:40'),
        ),
    ]
