# Generated by Django 4.1.1 on 2022-10-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_alter_ticket_cycle_alter_ticket_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='documentation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='15:21:50'),
        ),
    ]
