# Generated by Django 4.1.1 on 2022-10-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_ticket_documentation_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='17:37:48'),
        ),
    ]
