# Generated by Django 4.1.1 on 2022-10-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High'), ('Very High', 'Very High')], default='Low', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='17:50:29'),
        ),
    ]
