# Generated by Django 4.1.1 on 2022-10-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0045_expert_bio_alter_expert_address_alter_expert_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='10:56:13'),
        ),
    ]
