# Generated by Django 4.1.1 on 2022-10-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0047_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pics/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='11:30:47'),
        ),
    ]
