# Generated by Django 4.1.1 on 2022-10-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0048_alter_expert_profile_picture_alter_ticket_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expert',
            old_name='profile_picture',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='11:36:34'),
        ),
    ]
