# Generated by Django 4.1.1 on 2022-10-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0050_email_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.email'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='15:54:33'),
        ),
    ]
