# Generated by Django 4.1.1 on 2022-10-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0051_alter_expert_email_alter_ticket_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='email',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='15:56:52'),
        ),
        migrations.AddField(
            model_name='expert',
            name='email',
            field=models.ManyToManyField(to='tickets.email'),
        ),
    ]
