# Generated by Django 4.1.1 on 2022-10-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_remove_expert_email_alter_ticket_time_expert_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='15:58:36'),
        ),
    ]
