# Generated by Django 4.1.1 on 2022-10-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0053_alter_ticket_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='e',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='16:02:07'),
        ),
    ]
