# Generated by Django 4.1.1 on 2022-10-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0055_rename_e_email_email_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='16:05:32'),
        ),
    ]
