# Generated by Django 4.1.1 on 2022-10-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0058_alter_ticket_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='email',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='16:16:39'),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.AddField(
            model_name='expert',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
