# Generated by Django 4.1.1 on 2022-10-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0059_remove_expert_email_alter_ticket_time_delete_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='16:17:30'),
        ),
    ]
