# Generated by Django 4.1.1 on 2022-10-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0063_alter_ticket_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expert',
            name='email',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='16:22:46'),
        ),
        migrations.AddField(
            model_name='expert',
            name='email',
            field=models.ManyToManyField(to='tickets.email'),
        ),
    ]
