# Generated by Django 4.1.1 on 2022-10-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0065_remove_expert_email_alter_ticket_time_delete_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='social',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='16:43:39'),
        ),
    ]
