# Generated by Django 4.1.1 on 2022-10-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0067_remove_expert_social_expert_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='17:35:45'),
        ),
    ]
