# Generated by Django 4.1.1 on 2022-10-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0073_alter_ticket_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='anydesk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='14:26:17'),
        ),
    ]
