# Generated by Django 4.1.1 on 2022-10-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0089_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Liveware', 'Liveware'), ('Server', 'Server')], default='Software', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cycle',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Progress', 'Progress'), ('Closed', 'Closed')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High'), ('Very High', 'Very High')], default='Low', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='11:07:59'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='zone',
            field=models.CharField(max_length=100),
        ),
    ]
