# Generated by Django 4.1.1 on 2022-11-01 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0096_alter_ticket_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='submitter_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='09:34:49'),
        ),
    ]
