# Generated by Django 4.1.1 on 2022-11-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0100_alter_ticket_submitter_name_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='11:02:58'),
        ),
    ]
