# Generated by Django 4.1.1 on 2022-11-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0101_alter_ticket_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='11:23:06'),
        ),
    ]
