# Generated by Django 4.1.1 on 2022-11-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0107_alter_ticket_anydesk_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default='14:37:24'),
        ),
    ]
